config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'songs#index' #it's root link in the browser
  resources :songs #it's links in the browser
  devise_for :users #it's links in the browser,
  #example: http://localhost:3000/users/sign_up
  resources :comments
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :object, polymorphic: true
end

app/models/song.rb
class Song < ApplicationRecord
  mount_uploaders :songs, MusicUploader 
  serialize :songs, JSON
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
      before_action :authenticate_user!
    	before_action :find_comment,except:[:create]

    	def create
    		@comment = current_user.comments.build(comment_params)
        	redirect_back(fallback_location: root_path) if @comment.save
    	end

    	private

    	def comment_params
        	params.require(:comment).permit(:user_id,:object_id, :object_type, :text)
  		end

      def find_comment
        	@comment = Comment.find(params[:id])
      end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all #show all songs in site: localhost:3000/songs . 
  end

  def show
      @song = Song.find(params[:id]) #show song in site by ID : localhost:3000/songs/1 :)
  end
  #create/update/destroy in activeadmin
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/comments/_comment.html.erb
<%= f.text_area :text, size: "12x12" %><br /> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

   <%= link_to "Admin", new_admin_user_session_path %> |
    <% if user_signed_in? %>
   <%= link_to "Home", root_path %> |
   <%= link_to "Logout",  destroy_user_session_path, method: :delete %>
   <% else %>
   <%= link_to "Login", new_user_session_path %> |
   <%= link_to "Sign up", new_user_registration_path %>

    <% end %>

    <%= yield %>
  </body>
</html>

app/views/songs/_song.html.erb
<br>
Name:<br><%= song.name %><br>
Text:<br><%= song.text %><br>
Desc:<br><%= song.desc %><br>
<%= link_to "Read more", song_path(song.id) %>
<hr>

app/views/songs/index.html.erb
<%= render @songs %> <!--it is _song.html.erb -->

app/views/songs/show.html.erb
<br>
Name:<br><%= @song.name %><br>
Text:<br><%= @song.text %><br>
Desc:<br><%= @song.desc %><br>
<% if user_signed_in? %>

<% @song.songs.each do |bodya|%>
<br>
 <audio controls>
  <source src="<%= bodya.url %>" type="audio/mpeg">
 </audio>
<% end %>
<% else %>
Zalogintes` wtobi You can listen songs, thanks
<%= link_to "Login", new_user_session_path %>
<%= link_to "Sign up", new_user_registration_path %>
<% end %>

<!-- create comment -->

<%= form_for :comment, url:comments_path do |f| %>
<%= render 'comments/comment', f:f%>
<%= f.hidden_field :object_type, value: @song.class.name%>
<%= f.hidden_field :object_id, value: @song.id%>
<%= f.submit "Create" %>
<% end %>


<!-- show all comments -->

<% Comment.where(object: @song).each do |comment| %>
<br>User:
<%= comment.user.email.split('@').first %><br>
<%= comment.text%><hr>
<%end%>